/**
 * Autogenerated by Thrift Compiler (0.14.2)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
package com.fdu.server.genJava.generalize;


@javax.annotation.Generated(value = "Autogenerated by Thrift Compiler (0.14.2)", date = "2021-09-19")
public enum RESCODE implements org.apache.thrift.TEnum {
  _200(200),
  _500(500),
  _400(400);

  private final int value;

  private RESCODE(int value) {
    this.value = value;
  }

  /**
   * Get the integer value of this enum value, as defined in the Thrift IDL.
   */
  public int getValue() {
    return value;
  }

  /**
   * Find a the enum type by its integer value, as defined in the Thrift IDL.
   * @return null if the value is not found.
   */
  @org.apache.thrift.annotation.Nullable
  public static RESCODE findByValue(int value) { 
    switch (value) {
      case 200:
        return _200;
      case 500:
        return _500;
      case 400:
        return _400;
      default:
        return null;
    }
  }
}
