/**
 * Autogenerated by Thrift Compiler (0.14.2)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
package com.fdu.server.genJava.generalize;

import org.apache.thrift.annotation.Nullable;

@SuppressWarnings({"cast", "rawtypes", "serial", "unchecked", "unused"})
@javax.annotation.Generated(value = "Autogenerated by Thrift Compiler (0.14.2)", date = "2021-09-19")
public class Response implements org.apache.thrift.TBase<Response, Response._Fields>, java.io.Serializable, Cloneable, Comparable<Response> {
  private static final org.apache.thrift.protocol.TStruct STRUCT_DESC = new org.apache.thrift.protocol.TStruct("Response");

  private static final org.apache.thrift.protocol.TField RESPONE_CODE_FIELD_DESC = new org.apache.thrift.protocol.TField("responeCode", org.apache.thrift.protocol.TType.I32, (short)1);
  private static final org.apache.thrift.protocol.TField RESPONSE_JSON_FIELD_DESC = new org.apache.thrift.protocol.TField("responseJSON", org.apache.thrift.protocol.TType.STRING, (short)2);

  private static final org.apache.thrift.scheme.SchemeFactory STANDARD_SCHEME_FACTORY = new ResponseStandardSchemeFactory();
  private static final org.apache.thrift.scheme.SchemeFactory TUPLE_SCHEME_FACTORY = new ResponseTupleSchemeFactory();

  public @Nullable
  RESCODE responeCode; // required
  public @org.apache.thrift.annotation.Nullable java.nio.ByteBuffer responseJSON; // required

  /** The set of fields this struct contains, along with convenience methods for finding and manipulating them. */
  public enum _Fields implements org.apache.thrift.TFieldIdEnum {
    RESPONE_CODE((short)1, "responeCode"),
    RESPONSE_JSON((short)2, "responseJSON");

    private static final java.util.Map<String, _Fields> byName = new java.util.HashMap<String, _Fields>();

    static {
      for (_Fields field : java.util.EnumSet.allOf(_Fields.class)) {
        byName.put(field.getFieldName(), field);
      }
    }

    /**
     * Find the _Fields constant that matches fieldId, or null if its not found.
     */
    @org.apache.thrift.annotation.Nullable
    public static _Fields findByThriftId(int fieldId) {
      switch(fieldId) {
        case 1: // RESPONE_CODE
          return RESPONE_CODE;
        case 2: // RESPONSE_JSON
          return RESPONSE_JSON;
        default:
          return null;
      }
    }

    /**
     * Find the _Fields constant that matches fieldId, throwing an exception
     * if it is not found.
     */
    public static _Fields findByThriftIdOrThrow(int fieldId) {
      _Fields fields = findByThriftId(fieldId);
      if (fields == null) throw new IllegalArgumentException("Field " + fieldId + " doesn't exist!");
      return fields;
    }

    /**
     * Find the _Fields constant that matches name, or null if its not found.
     */
    @org.apache.thrift.annotation.Nullable
    public static _Fields findByName(String name) {
      return byName.get(name);
    }

    private final short _thriftId;
    private final String _fieldName;

    _Fields(short thriftId, String fieldName) {
      _thriftId = thriftId;
      _fieldName = fieldName;
    }

    public short getThriftFieldId() {
      return _thriftId;
    }

    public String getFieldName() {
      return _fieldName;
    }
  }

  // isset id assignments
  public static final java.util.Map<_Fields, org.apache.thrift.meta_data.FieldMetaData> metaDataMap;
  static {
    java.util.Map<_Fields, org.apache.thrift.meta_data.FieldMetaData> tmpMap = new java.util.EnumMap<_Fields, org.apache.thrift.meta_data.FieldMetaData>(_Fields.class);
    tmpMap.put(_Fields.RESPONE_CODE, new org.apache.thrift.meta_data.FieldMetaData("responeCode", org.apache.thrift.TFieldRequirementType.REQUIRED, 
        new org.apache.thrift.meta_data.FieldValueMetaData(org.apache.thrift.protocol.TType.ENUM        , "RESCODE")));
    tmpMap.put(_Fields.RESPONSE_JSON, new org.apache.thrift.meta_data.FieldMetaData("responseJSON", org.apache.thrift.TFieldRequirementType.REQUIRED, 
        new org.apache.thrift.meta_data.FieldValueMetaData(org.apache.thrift.protocol.TType.STRING        , true)));
    metaDataMap = java.util.Collections.unmodifiableMap(tmpMap);
    org.apache.thrift.meta_data.FieldMetaData.addStructMetaDataMap(Response.class, metaDataMap);
  }

  public Response() {
  }

  public Response(
    RESCODE responeCode,
    java.nio.ByteBuffer responseJSON)
  {
    this();
    this.responeCode = responeCode;
    this.responseJSON = org.apache.thrift.TBaseHelper.copyBinary(responseJSON);
  }

  /**
   * Performs a deep copy on <i>other</i>.
   */
  public Response(Response other) {
    if (other.isSetResponeCode()) {
      this.responeCode = other.responeCode;
    }
    if (other.isSetResponseJSON()) {
      this.responseJSON = org.apache.thrift.TBaseHelper.copyBinary(other.responseJSON);
    }
  }

  public Response deepCopy() {
    return new Response(this);
  }

  @Override
  public void clear() {
    this.responeCode = null;
    this.responseJSON = null;
  }

  @org.apache.thrift.annotation.Nullable
  public RESCODE getResponeCode() {
    return this.responeCode;
  }

  public Response setResponeCode(@org.apache.thrift.annotation.Nullable RESCODE responeCode) {
    this.responeCode = responeCode;
    return this;
  }

  public void unsetResponeCode() {
    this.responeCode = null;
  }

  /** Returns true if field responeCode is set (has been assigned a value) and false otherwise */
  public boolean isSetResponeCode() {
    return this.responeCode != null;
  }

  public void setResponeCodeIsSet(boolean value) {
    if (!value) {
      this.responeCode = null;
    }
  }

  public byte[] getResponseJSON() {
    setResponseJSON(org.apache.thrift.TBaseHelper.rightSize(responseJSON));
    return responseJSON == null ? null : responseJSON.array();
  }

  public java.nio.ByteBuffer bufferForResponseJSON() {
    return org.apache.thrift.TBaseHelper.copyBinary(responseJSON);
  }

  public Response setResponseJSON(byte[] responseJSON) {
    this.responseJSON = responseJSON == null ? (java.nio.ByteBuffer)null   : java.nio.ByteBuffer.wrap(responseJSON.clone());
    return this;
  }

  public Response setResponseJSON(@org.apache.thrift.annotation.Nullable java.nio.ByteBuffer responseJSON) {
    this.responseJSON = org.apache.thrift.TBaseHelper.copyBinary(responseJSON);
    return this;
  }

  public void unsetResponseJSON() {
    this.responseJSON = null;
  }

  /** Returns true if field responseJSON is set (has been assigned a value) and false otherwise */
  public boolean isSetResponseJSON() {
    return this.responseJSON != null;
  }

  public void setResponseJSONIsSet(boolean value) {
    if (!value) {
      this.responseJSON = null;
    }
  }

  public void setFieldValue(_Fields field, @org.apache.thrift.annotation.Nullable Object value) {
    switch (field) {
    case RESPONE_CODE:
      if (value == null) {
        unsetResponeCode();
      } else {
        setResponeCode((RESCODE)value);
      }
      break;

    case RESPONSE_JSON:
      if (value == null) {
        unsetResponseJSON();
      } else {
        if (value instanceof byte[]) {
          setResponseJSON((byte[])value);
        } else {
          setResponseJSON((java.nio.ByteBuffer)value);
        }
      }
      break;

    }
  }

  @org.apache.thrift.annotation.Nullable
  public Object getFieldValue(_Fields field) {
    switch (field) {
    case RESPONE_CODE:
      return getResponeCode();

    case RESPONSE_JSON:
      return getResponseJSON();

    }
    throw new IllegalStateException();
  }

  /** Returns true if field corresponding to fieldID is set (has been assigned a value) and false otherwise */
  public boolean isSet(_Fields field) {
    if (field == null) {
      throw new IllegalArgumentException();
    }

    switch (field) {
    case RESPONE_CODE:
      return isSetResponeCode();
    case RESPONSE_JSON:
      return isSetResponseJSON();
    }
    throw new IllegalStateException();
  }

  @Override
  public boolean equals(Object that) {
    if (that instanceof Response)
      return this.equals((Response)that);
    return false;
  }

  public boolean equals(Response that) {
    if (that == null)
      return false;
    if (this == that)
      return true;

    boolean this_present_responeCode = true && this.isSetResponeCode();
    boolean that_present_responeCode = true && that.isSetResponeCode();
    if (this_present_responeCode || that_present_responeCode) {
      if (!(this_present_responeCode && that_present_responeCode))
        return false;
      if (!this.responeCode.equals(that.responeCode))
        return false;
    }

    boolean this_present_responseJSON = true && this.isSetResponseJSON();
    boolean that_present_responseJSON = true && that.isSetResponseJSON();
    if (this_present_responseJSON || that_present_responseJSON) {
      if (!(this_present_responseJSON && that_present_responseJSON))
        return false;
      if (!this.responseJSON.equals(that.responseJSON))
        return false;
    }

    return true;
  }

  @Override
  public int hashCode() {
    int hashCode = 1;

    hashCode = hashCode * 8191 + ((isSetResponeCode()) ? 131071 : 524287);
    if (isSetResponeCode())
      hashCode = hashCode * 8191 + responeCode.getValue();

    hashCode = hashCode * 8191 + ((isSetResponseJSON()) ? 131071 : 524287);
    if (isSetResponseJSON())
      hashCode = hashCode * 8191 + responseJSON.hashCode();

    return hashCode;
  }

  @Override
  public int compareTo(Response other) {
    if (!getClass().equals(other.getClass())) {
      return getClass().getName().compareTo(other.getClass().getName());
    }

    int lastComparison = 0;

    lastComparison = Boolean.compare(isSetResponeCode(), other.isSetResponeCode());
    if (lastComparison != 0) {
      return lastComparison;
    }
    if (isSetResponeCode()) {
      lastComparison = org.apache.thrift.TBaseHelper.compareTo(this.responeCode, other.responeCode);
      if (lastComparison != 0) {
        return lastComparison;
      }
    }
    lastComparison = Boolean.compare(isSetResponseJSON(), other.isSetResponseJSON());
    if (lastComparison != 0) {
      return lastComparison;
    }
    if (isSetResponseJSON()) {
      lastComparison = org.apache.thrift.TBaseHelper.compareTo(this.responseJSON, other.responseJSON);
      if (lastComparison != 0) {
        return lastComparison;
      }
    }
    return 0;
  }

  @org.apache.thrift.annotation.Nullable
  public _Fields fieldForId(int fieldId) {
    return _Fields.findByThriftId(fieldId);
  }

  public void read(org.apache.thrift.protocol.TProtocol iprot) throws org.apache.thrift.TException {
    scheme(iprot).read(iprot, this);
  }

  public void write(org.apache.thrift.protocol.TProtocol oprot) throws org.apache.thrift.TException {
    scheme(oprot).write(oprot, this);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder("Response(");
    boolean first = true;

    sb.append("responeCode:");
    if (this.responeCode == null) {
      sb.append("null");
    } else {
      sb.append(this.responeCode);
    }
    first = false;
    if (!first) sb.append(", ");
    sb.append("responseJSON:");
    if (this.responseJSON == null) {
      sb.append("null");
    } else {
      org.apache.thrift.TBaseHelper.toString(this.responseJSON, sb);
    }
    first = false;
    sb.append(")");
    return sb.toString();
  }

  public void validate() throws org.apache.thrift.TException {
    // check for required fields
    if (responeCode == null) {
      throw new org.apache.thrift.protocol.TProtocolException("Required field 'responeCode' was not present! Struct: " + toString());
    }
    if (responseJSON == null) {
      throw new org.apache.thrift.protocol.TProtocolException("Required field 'responseJSON' was not present! Struct: " + toString());
    }
    // check for sub-struct validity
  }

  private void writeObject(java.io.ObjectOutputStream out) throws java.io.IOException {
    try {
      write(new org.apache.thrift.protocol.TCompactProtocol(new org.apache.thrift.transport.TIOStreamTransport(out)));
    } catch (org.apache.thrift.TException te) {
      throw new java.io.IOException(te);
    }
  }

  private void readObject(java.io.ObjectInputStream in) throws java.io.IOException, ClassNotFoundException {
    try {
      read(new org.apache.thrift.protocol.TCompactProtocol(new org.apache.thrift.transport.TIOStreamTransport(in)));
    } catch (org.apache.thrift.TException te) {
      throw new java.io.IOException(te);
    }
  }

  private static class ResponseStandardSchemeFactory implements org.apache.thrift.scheme.SchemeFactory {
    public ResponseStandardScheme getScheme() {
      return new ResponseStandardScheme();
    }
  }

  private static class ResponseStandardScheme extends org.apache.thrift.scheme.StandardScheme<Response> {

    public void read(org.apache.thrift.protocol.TProtocol iprot, Response struct) throws org.apache.thrift.TException {
      org.apache.thrift.protocol.TField schemeField;
      iprot.readStructBegin();
      while (true)
      {
        schemeField = iprot.readFieldBegin();
        if (schemeField.type == org.apache.thrift.protocol.TType.STOP) { 
          break;
        }
        switch (schemeField.id) {
          case 1: // RESPONE_CODE
            if (schemeField.type == org.apache.thrift.protocol.TType.I32) {
              struct.responeCode = RESCODE.findByValue(iprot.readI32());
              struct.setResponeCodeIsSet(true);
            } else { 
              org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
            }
            break;
          case 2: // RESPONSE_JSON
            if (schemeField.type == org.apache.thrift.protocol.TType.STRING) {
              struct.responseJSON = iprot.readBinary();
              struct.setResponseJSONIsSet(true);
            } else { 
              org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
            }
            break;
          default:
            org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
        }
        iprot.readFieldEnd();
      }
      iprot.readStructEnd();

      // check for required fields of primitive type, which can't be checked in the validate method
      struct.validate();
    }

    public void write(org.apache.thrift.protocol.TProtocol oprot, Response struct) throws org.apache.thrift.TException {
      struct.validate();

      oprot.writeStructBegin(STRUCT_DESC);
      if (struct.responeCode != null) {
        oprot.writeFieldBegin(RESPONE_CODE_FIELD_DESC);
        oprot.writeI32(struct.responeCode.getValue());
        oprot.writeFieldEnd();
      }
      if (struct.responseJSON != null) {
        oprot.writeFieldBegin(RESPONSE_JSON_FIELD_DESC);
        oprot.writeBinary(struct.responseJSON);
        oprot.writeFieldEnd();
      }
      oprot.writeFieldStop();
      oprot.writeStructEnd();
    }

  }

  private static class ResponseTupleSchemeFactory implements org.apache.thrift.scheme.SchemeFactory {
    public ResponseTupleScheme getScheme() {
      return new ResponseTupleScheme();
    }
  }

  private static class ResponseTupleScheme extends org.apache.thrift.scheme.TupleScheme<Response> {

    @Override
    public void write(org.apache.thrift.protocol.TProtocol prot, Response struct) throws org.apache.thrift.TException {
      org.apache.thrift.protocol.TTupleProtocol oprot = (org.apache.thrift.protocol.TTupleProtocol) prot;
      oprot.writeI32(struct.responeCode.getValue());
      oprot.writeBinary(struct.responseJSON);
    }

    @Override
    public void read(org.apache.thrift.protocol.TProtocol prot, Response struct) throws org.apache.thrift.TException {
      org.apache.thrift.protocol.TTupleProtocol iprot = (org.apache.thrift.protocol.TTupleProtocol) prot;
      struct.responeCode = RESCODE.findByValue(iprot.readI32());
      struct.setResponeCodeIsSet(true);
      struct.responseJSON = iprot.readBinary();
      struct.setResponseJSONIsSet(true);
    }
  }

  private static <S extends org.apache.thrift.scheme.IScheme> S scheme(org.apache.thrift.protocol.TProtocol proto) {
    return (org.apache.thrift.scheme.StandardScheme.class.equals(proto.getScheme()) ? STANDARD_SCHEME_FACTORY : TUPLE_SCHEME_FACTORY).getScheme();
  }
}

